config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :boxes do 
    member do
      get :join
      get :leave
    end
  end

  root 'sessions#login'

  get 'login' => 'sessions#login'
  post 'login' => 'sessions#verify'
  get 'logout' => 'sessions#logout'

end

app/models/box.rb
class Box < ActiveRecord::Base
	has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :box
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :get_user
  before_action :redirect_unless_loggedin, except: [:new, :create]


  def get_user
  	if session[:user_id]
  		@current_user = User.find(session[:user_id])
  	else
  		@current_user = nil
  	end
  end


  def redirect_unless_loggedin
      redirect_to root_path unless @current_user
  end
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_action :set_box, only: [:show, :edit, :update, :destroy, :join]

  # GET /boxes
  # GET /boxes.json
  def index
    @boxes = Box.all
  end

  # GET /boxes/1
  # GET /boxes/1.json
  def show
    @box.users << @current_user
    @box.save
  end

  def leave
    @current_user.box = nil
    @current_user.save
    redirect_to :boxes
  end

  # GET /boxes/new
  def new
    @box = Box.new
  end

  # GET /boxes/1/edit
  def edit
  end

  # POST /boxes
  # POST /boxes.json
  def create
    @box = Box.new(box_params)

    respond_to do |format|
      if @box.save
        format.html { redirect_to @box, notice: 'Box was successfully created.' }
        format.json { render :show, status: :created, location: @box }
      else
        format.html { render :new }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boxes/1
  # PATCH/PUT /boxes/1.json
  def update
    respond_to do |format|
      if @box.update(box_params)
        format.html { redirect_to @box, notice: 'Box was successfully updated.' }
        format.json { render :show, status: :ok, location: @box }
      else
        format.html { render :edit }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1
  # DELETE /boxes/1.json
  def destroy
    @box.destroy
    respond_to do |format|
      format.html { redirect_to boxes_url, notice: 'Box was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_box
      @box = Box.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def box_params
      params.require(:box).permit(:title, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_action :redirect_unless_loggedin

	def login
	end

	def logout
		session[:user_id] = nil
	end

	def verify
		user = User.find_by(email: params[:email])
		if user
			session[:user_id] = user.id
			redirect_to :boxes, :id => user.id
		else
			redirect_to :login
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :alias, :box_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boxes/_form.html.erb
<%= form_for(@box) do |f| %>
  <% if @box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@box.errors.count, "error") %> prohibited this box from being saved:</h2>

      <ul>
      <% @box.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boxes/edit.html.erb
<h1>Editing Box</h1>

<%= render 'form' %>

<%= link_to 'Show', @box %> |
<%= link_to 'Back', boxes_path %>

app/views/boxes/index.html.erb
<p id="notice"><%= notice %></p>

<nav>
  <% if @current_user %>
    Hi, <%= @current_user.name %>! | <%= link_to "Logout", logout_path %>
  <% else %>
    <%= link_to "Login", login_path %>
  <% end %> 
  </nav> 
  
<h1>HonestBox</h1>

<!-- <table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boxes.each do |box| %>
      <div>
        <br><%= box.title %></td>
        <br><%= box.description %></td>
        <br><%= link_to 'Join', box %></td>

    <td><%= link_to 'Edit', edit_box_path(box) %></td>
        <td><%= link_to 'Destroy', box, method: :delete, data: { confirm: 'Are you sure?' } %></td>

    <td><%# link_to 'Edit', edit_box_path(box) %></td>
        <td><%# link_to 'Destroy', box, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </div>
    <% end %> 
  </tbody>
</table> -->

<section>
<% @boxes.each do |box| %>
  <div>
  <%= box.title %>
  <br>
  <%= box.description %>
  </br>
  <br>
  <%= link_to 'Join', box %>
  </br>
  <!-- <br>
  <%= link_to 'Edit', edit_box_path(box) %>
  </br> -->
  </div>
  <% end %>
</section>



<br>

<p>
<%= link_to 'New Box', new_box_path %>
</p>

<!-- /*<link rel="stylesheet" type="text/css" href="boxes.css">

<section>
  <div>
  Suggestion Box: Zak the Baker
  </div>

  <div>
  Wyncode Retrospective
  </div>

  <div>
  Ideas for Pitch Day
  </div>

  <div>Suggestion Box: The LAB Miami
  </div>
</section>

<section>
<div>Thoughts on Wynwood Street Art</div>
<div>Sports Box</div>
<div>Art Box</div>
<div>Music Box</div>
</section>

</html> -->

app/views/boxes/new.html.erb
<div class="" ="page">

<h1 class="top-bar">New Box</h1>

<%= render 'form' %>

<%= link_to 'Back', boxes_path %>

</div>

app/views/boxes/show.html.erb
<!-- <h2>
<%= @box.title %>
</h2>
<form class="add-item">
	<input type="text">
	<input type="submit" class="pull-right" value="Submit">
</form>
<br>
<div id="chatBox" chat-title="<%= @box.title %>">
 	<ul>
	</ul>
</div> -->

<!-- <p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @box.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @box.description %>
</p>

<%# link_to 'Edit', edit_box_path(@box) %> |
<%# link_to 'Back', boxes_path %> -->

<nav>
<% if @current_user %>
	Hi, <%= @current_user.name %>! | <%= link_to "Logout", logout_path %>
<% else %>
	<%= link_to "Login", login_path %>
<% end %>	
</nav>

<div class="main">
	<h1 class="top-bar">Wyncode Suggestion Box</h1>

	<div id="chat-box" chat-title="<%= @box.title %>">
		<ul>
			
		</ul>
	</div>

	<form class="add-item">
		<input type="text" class="write">
		<input type="submit" class="pull-right" value="enter">
	</form>

</div>

<div class="people">

<h2 id="people-bar" user="<%= @current_user.name %>"> Honest Folks </h2>

People signed in to this particular box will be listed here:
<br>
<% @box.users.each do |user| %>
	<br><%= user.name %>
<% end %>

</div>

<div class="leave">
<%= link_to "Leave", leave_box_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HonestBox</title>
  <script src='https://cdn.firebase.com/js/client/2.0.4/firebase.js'></script>
  <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Alias</th>
      <th>Box</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
       <!--  <td><%= user.alias %></td> -->
      <!--   <td><%= user.box %></td> -->
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', login_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Alias:</strong>
  <%= @user.alias %>
</p>

<p>
  <strong>Box:</strong>
  <%= @user.box %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', login_path %>